"""Time-domain solvers and hydrodynamic-memory helpers."""

from offshore_energy_sim.time_domain.cases import TimeDomainSimulationConfig
from offshore_energy_sim.time_domain.excitation import (
    cosine_ramp,
    external_force_time_series,
    harmonic_force_time_series,
    jonswap_spectrum,
    pierson_moskowitz_spectrum,
    random_wave_phases,
    spectral_component_widths,
    spectral_wave_amplitudes,
    spectral_wave_force_time_series,
    wave_elevation_time_series,
    wave_spectrum_density,
)
from offshore_energy_sim.time_domain.hydrodynamic_memory import (
    apply_radiation_frequency_window,
    estimate_infinite_frequency_added_mass,
    estimate_infinite_frequency_added_mass_from_irf,
    project_matrix_series_positive_semidefinite,
    project_symmetric_positive_semidefinite,
    radiation_coefficients_from_discrete_irf,
    radiation_coefficients_from_irf,
    radiation_frequency_window_weights,
    radiation_irf_from_damping,
)
from offshore_energy_sim.time_domain.postprocess import (
    fit_harmonic_amplitude,
    fit_multi_harmonic_amplitudes,
    harmonic_amplitude_error,
    harmonic_component_variance,
    relative_l2_error,
    zero_mean_rms,
)
from offshore_energy_sim.time_domain.rodm_hydrodynamics import (
    TimeDomainHydrodynamicTerms,
    prepare_rodm_time_domain_hydrodynamic_terms,
)
from offshore_energy_sim.time_domain.solver import (
    LinearTimeDomainResult,
    RodmTimeDomainResult,
    direct_convolution_memory_force,
    solve_linear_time_domain,
    solve_linear_time_domain_rk4,
    solve_rodm_time_domain_case,
)

__all__ = [
    "LinearTimeDomainResult",
    "RodmTimeDomainResult",
    "TimeDomainSimulationConfig",
    "TimeDomainHydrodynamicTerms",
    "apply_radiation_frequency_window",
    "cosine_ramp",
    "direct_convolution_memory_force",
    "estimate_infinite_frequency_added_mass",
    "estimate_infinite_frequency_added_mass_from_irf",
    "external_force_time_series",
    "fit_harmonic_amplitude",
    "fit_multi_harmonic_amplitudes",
    "harmonic_amplitude_error",
    "harmonic_component_variance",
    "harmonic_force_time_series",
    "jonswap_spectrum",
    "prepare_rodm_time_domain_hydrodynamic_terms",
    "pierson_moskowitz_spectrum",
    "project_matrix_series_positive_semidefinite",
    "project_symmetric_positive_semidefinite",
    "random_wave_phases",
    "radiation_coefficients_from_discrete_irf",
    "radiation_coefficients_from_irf",
    "radiation_frequency_window_weights",
    "radiation_irf_from_damping",
    "solve_linear_time_domain",
    "solve_linear_time_domain_rk4",
    "solve_rodm_time_domain_case",
    "spectral_component_widths",
    "spectral_wave_amplitudes",
    "spectral_wave_force_time_series",
    "relative_l2_error",
    "wave_elevation_time_series",
    "wave_spectrum_density",
    "zero_mean_rms",
]
