"""Structural matrix and connection models."""

from offshore_energy_sim.structure.assembly import (
    add_local_matrix_in_place,
    assemble_local_matrix,
    calculate_2d_node_positions_descending,
    calculate_node_positions,
    node_dof_indices,
)
from offshore_energy_sim.structure.connectors import add_two_node_coupling_in_place
from offshore_energy_sim.structure.hinges import (
    ExplicitHingeSpec,
    HingeLineSpec,
    assemble_explicit_hinges_sparse,
    apply_explicit_hinge_in_place,
    apply_explicit_hinges_in_place,
    add_hinge_connections_in_place,
    apply_hinge_line_in_place,
    build_hinged_stiffness,
    calculate_column_node_indices,
    generate_column_elements,
    hinge_coupling_matrix,
    read_plain_upper_triangle_stiffness_matrix,
    read_symmetric_element_stiffness_matrix,
    remove_hinge_line_elements_in_place,
    remove_element_stiffness_in_place,
)
from offshore_energy_sim.structure.matrix_io import (
    AbaqusMatrixSummary,
    read_abaqus_matrix_dense,
    read_abaqus_matrix_sparse,
    scan_abaqus_matrix_file,
)
from offshore_energy_sim.structure.modular_grid import (
    ModuleControlPoint,
    ModuleGridSpec,
    drop_duplicate_module_interfaces,
    generate_grid_hinge_specs,
    generate_master_nodes_one_based,
    generate_module_center_control_points,
    generate_x_hinge_node_pairs,
    generate_y_hinge_node_pairs,
)
from offshore_energy_sim.structure.rodm_reduction import (
    StructuralReductionResult,
    prepare_structural_reduction,
)

__all__ = [
    "AbaqusMatrixSummary",
    "ExplicitHingeSpec",
    "HingeLineSpec",
    "ModuleControlPoint",
    "ModuleGridSpec",
    "StructuralReductionResult",
    "add_hinge_connections_in_place",
    "add_local_matrix_in_place",
    "add_two_node_coupling_in_place",
    "assemble_explicit_hinges_sparse",
    "apply_explicit_hinge_in_place",
    "apply_explicit_hinges_in_place",
    "apply_hinge_line_in_place",
    "assemble_local_matrix",
    "build_hinged_stiffness",
    "calculate_2d_node_positions_descending",
    "calculate_column_node_indices",
    "calculate_node_positions",
    "drop_duplicate_module_interfaces",
    "generate_column_elements",
    "generate_grid_hinge_specs",
    "generate_master_nodes_one_based",
    "generate_module_center_control_points",
    "generate_x_hinge_node_pairs",
    "generate_y_hinge_node_pairs",
    "hinge_coupling_matrix",
    "node_dof_indices",
    "prepare_structural_reduction",
    "read_abaqus_matrix_dense",
    "read_abaqus_matrix_sparse",
    "read_plain_upper_triangle_stiffness_matrix",
    "read_symmetric_element_stiffness_matrix",
    "remove_hinge_line_elements_in_place",
    "remove_element_stiffness_in_place",
    "scan_abaqus_matrix_file",
]
