"""Run SEREP-ridge regularization sensitivity for the NU10 study.

This workflow reuses the hydrodynamic NetCDF files generated by
``run_serep_nonuniform_wavelength_sweep.py``. It does not rerun Capytaine.
Only the structural SEREP-ridge regularization parameter is varied.
"""

from __future__ import annotations

from pathlib import Path
import argparse
import csv
import json
import sys
import time

import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[0]
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(SCRIPT_DIR))

import run_serep_nonuniform_wavelength_sweep as sweep  # noqa: E402
from offshore_energy_sim.core import MasterNodeRule, RodmFrequencyCase  # noqa: E402
from offshore_energy_sim.postprocess.reference_case_300 import extract_centerline_heave  # noqa: E402
from offshore_energy_sim.solver import solve_rodm_frequency_case  # noqa: E402


OUTPUT_ROOT = REPO_ROOT / "results" / "serep_ridge_lambda_sensitivity"
RESPONSE_DIR = OUTPUT_ROOT / "responses"
TABLE_DIR = OUTPUT_ROOT / "tables"
FIGURE_DIR = OUTPUT_ROOT / "figures"
REPORT_PATH = OUTPUT_ROOT / "serep_ridge_lambda_sensitivity_report.md"

DEFAULT_RELATIVE_LAMBDAS = (1.0e-14, 1.0e-15, 1.0e-16, 1.0e-17, 1.0e-18)
DEFAULT_WAVELENGTHS_M = (120, 180, 240, 300)
SOURCE_WAVELENGTHS_M = tuple(int(value) for value in sweep.DEFAULT_WAVELENGTHS_M)
BASELINE_LAMBDA = 1.0e-16

COLORS = {
    "uniform_U10": "#1f77b4",
    "NU10_center_refined": "#ff7f0e",
    "NU10_edge_mild": "#9467bd",
    "NU10_bow_refined": "#d62728",
}


def parse_float_list(text: str | None, default: tuple[float, ...]) -> tuple[float, ...]:
    if not text:
        return default
    values = tuple(float(item) for item in text.replace(",", " ").split())
    if not values:
        raise ValueError("at least one value is required")
    return values


def parse_int_list(text: str | None, default: tuple[int, ...]) -> tuple[int, ...]:
    if not text:
        return default
    values = tuple(int(float(item)) for item in text.replace(",", " ").split())
    if not values:
        raise ValueError("at least one value is required")
    return values


def lambda_label(value: float) -> str:
    return f"{value:.0e}".replace("+", "")


def lambda_dir(value: float) -> Path:
    return RESPONSE_DIR / f"lambda_{lambda_label(value)}"


def response_path(layout_id: str, wavelength_m: int, relative_lambda: float) -> Path:
    return lambda_dir(relative_lambda) / layout_id / f"{layout_id}_wavelength_{wavelength_m}m_response.npy"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, object]]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    return path


def selected_layouts() -> tuple[sweep.LayoutSpec, ...]:
    return sweep.selected_layouts(include_searched=False)


def hydro_config(layout: sweep.LayoutSpec) -> sweep.ArrayHydrodynamicsConfig:
    config = sweep.hydro_config(layout, SOURCE_WAVELENGTHS_M, n_jobs=1)
    if not config.output_path.exists():
        raise FileNotFoundError(
            f"Missing hydrodynamic file for {layout.layout_id}: {config.output_path}. "
            "Run scripts/run_serep_nonuniform_wavelength_sweep.py first."
        )
    return config


def frequency_index(wavelength_m: int) -> int:
    try:
        return SOURCE_WAVELENGTHS_M.index(int(wavelength_m))
    except ValueError as exc:
        raise ValueError(
            f"wavelength {wavelength_m} m is not in the source NC wavelength list "
            f"{SOURCE_WAVELENGTHS_M}"
        ) from exc


def build_case(
    *,
    layout: sweep.LayoutSpec,
    hydro_path: Path,
    master_nodes: tuple[int, ...],
    wavelength_m: int,
    relative_lambda: float,
) -> RodmFrequencyCase:
    return RodmFrequencyCase(
        case_id=f"{layout.layout_id}_{wavelength_m}m_serep_ridge_{lambda_label(relative_lambda)}",
        total_nodes=793,
        full_dofs_per_node=6,
        retained_dofs_per_node=5,
        removed_full_dofs_zero_based=(5,),
        master_node_rule=MasterNodeRule(first_node=master_nodes[0], node_interval=1, count=len(master_nodes)),
        master_nodes_one_based=master_nodes,
        hydrodynamic_dataset=hydro_path,
        structural_matrices=sweep.base.structural_paths(),
        hydrodynamic_nodes=len(master_nodes),
        hydrodynamic_dof_to_remove_zero_based=5,
        structural_reduction_method="serep_ridge",
        preserve_master_order=True,
        serep_ridge_relative_lambda=relative_lambda,
        frequency_index=frequency_index(wavelength_m),
        reverse_hydrodynamic_node_order=False,
    )


def geometry_and_master_nodes(
    layout: sweep.LayoutSpec,
    config: sweep.ArrayHydrodynamicsConfig,
) -> tuple[list[dict[str, object]], tuple[int, ...]]:
    rows = sweep.geometry_rows(layout, config)
    return rows, sweep.master_nodes_from_geometry(rows)


def write_master_node_tables(layouts: tuple[sweep.LayoutSpec, ...]) -> Path:
    rows: list[dict[str, object]] = []
    for layout in layouts:
        config = hydro_config(layout)
        geometry, _ = geometry_and_master_nodes(layout, config)
        for row in geometry:
            rows.append(
                {
                    "layout_id": layout.layout_id,
                    "display_name": layout.display_name,
                    "module_id": row["module_id"],
                    "module_length_m": row["module_length_m"],
                    "center_x_m": row["center_x_m"],
                    "selected_node_id": row["selected_node_id"],
                    "selected_node_x_m": row["selected_node_x_m"],
                    "abs_error_m": row["abs_error_m"],
                }
            )
    return write_csv(TABLE_DIR / "lambda_sensitivity_master_nodes.csv", rows)


def solve_all(
    *,
    relative_lambdas: tuple[float, ...],
    wavelengths_m: tuple[int, ...],
    force_response: bool,
) -> dict[tuple[str, int, str], Path]:
    layouts = selected_layouts()
    response_paths: dict[tuple[str, int, str], Path] = {}
    total = len(relative_lambdas) * len(layouts) * len(wavelengths_m)
    completed = 0
    start = time.perf_counter()

    for relative_lambda in relative_lambdas:
        label = lambda_label(relative_lambda)
        for layout in layouts:
            config = hydro_config(layout)
            _, master_nodes = geometry_and_master_nodes(layout, config)
            for wavelength_m in wavelengths_m:
                completed += 1
                path = response_path(layout.layout_id, wavelength_m, relative_lambda)
                response_paths[(layout.layout_id, wavelength_m, label)] = path
                if path.exists() and not force_response:
                    print(f"[{completed:03d}/{total:03d}] reuse {label} {layout.layout_id} {wavelength_m} m")
                    continue
                path.parent.mkdir(parents=True, exist_ok=True)
                print(f"[{completed:03d}/{total:03d}] solve {label} {layout.layout_id} {wavelength_m} m")
                case = build_case(
                    layout=layout,
                    hydro_path=config.output_path,
                    master_nodes=master_nodes,
                    wavelength_m=wavelength_m,
                    relative_lambda=relative_lambda,
                )
                result = solve_rodm_frequency_case(case)
                np.save(path, result.global_displacement)

    elapsed = time.perf_counter() - start
    (OUTPUT_ROOT / "run_manifest.json").write_text(
        json.dumps(
            {
                "elapsed_seconds": elapsed,
                "relative_lambdas": [lambda_label(value) for value in relative_lambdas],
                "wavelengths_m": list(wavelengths_m),
                "layouts": [layout.layout_id for layout in layouts],
                "source_wavelengths_m": list(SOURCE_WAVELENGTHS_M),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return response_paths


def load_heave(path: Path) -> tuple[np.ndarray, np.ndarray]:
    return extract_centerline_heave(np.load(path))


def roughness(values: np.ndarray) -> float:
    if values.size < 3:
        return 0.0
    return float(np.max(np.abs(np.diff(values, n=2))))


def compute_metrics(
    *,
    relative_lambdas: tuple[float, ...],
    wavelengths_m: tuple[int, ...],
) -> tuple[Path, Path, Path, Path]:
    layouts = selected_layouts()
    metric_rows: list[dict[str, object]] = []
    drift_rows: list[dict[str, object]] = []
    for relative_lambda in relative_lambdas:
        label = lambda_label(relative_lambda)
        for wavelength_m in wavelengths_m:
            _, heave_ref = load_heave(response_path("U30_reference", wavelength_m, relative_lambda))
            _, heave_u10 = load_heave(response_path("uniform_U10", wavelength_m, relative_lambda))
            u10_rmse = float(np.sqrt(np.mean((heave_u10 - heave_ref) ** 2)))
            for layout in layouts:
                x, heave = load_heave(response_path(layout.layout_id, wavelength_m, relative_lambda))
                delta = heave - heave_ref
                rmse = float(np.sqrt(np.mean(delta**2)))
                max_abs = float(np.max(np.abs(delta)))
                improvement = (u10_rmse - rmse) / u10_rmse * 100.0 if u10_rmse else 0.0
                metric_rows.append(
                    {
                        "relative_lambda": relative_lambda,
                        "lambda_label": label,
                        "layout_id": layout.layout_id,
                        "display_name": layout.display_name,
                        "category": layout.category,
                        "wavelength_m": wavelength_m,
                        "rmse_vs_same_lambda_U30": rmse,
                        "max_abs_vs_same_lambda_U30": max_abs,
                        "roughness": roughness(heave),
                        "improvement_vs_same_lambda_U10_percent": improvement,
                        "response_path": response_path(layout.layout_id, wavelength_m, relative_lambda),
                    }
                )

                if abs(relative_lambda - BASELINE_LAMBDA) < BASELINE_LAMBDA * 1.0e-12:
                    drift_rmse = 0.0
                    drift_max = 0.0
                else:
                    _, heave_base = load_heave(response_path(layout.layout_id, wavelength_m, BASELINE_LAMBDA))
                    drift_delta = heave - heave_base
                    drift_rmse = float(np.sqrt(np.mean(drift_delta**2)))
                    drift_max = float(np.max(np.abs(drift_delta)))
                drift_rows.append(
                    {
                        "relative_lambda": relative_lambda,
                        "lambda_label": label,
                        "layout_id": layout.layout_id,
                        "display_name": layout.display_name,
                        "wavelength_m": wavelength_m,
                        "rmse_vs_lambda_1e-16": drift_rmse,
                        "max_abs_vs_lambda_1e-16": drift_max,
                    }
                )

    metrics_path = write_csv(TABLE_DIR / "lambda_sensitivity_by_wavelength.csv", metric_rows)
    drift_path = write_csv(TABLE_DIR / "lambda_response_drift_vs_1e-16.csv", drift_rows)

    summary_rows: list[dict[str, object]] = []
    for relative_lambda in relative_lambdas:
        label = lambda_label(relative_lambda)
        for layout in layouts:
            rows = [
                row
                for row in metric_rows
                if row["lambda_label"] == label and row["layout_id"] == layout.layout_id
            ]
            summary_rows.append(
                {
                    "relative_lambda": relative_lambda,
                    "lambda_label": label,
                    "layout_id": layout.layout_id,
                    "display_name": layout.display_name,
                    "mean_rmse_vs_same_lambda_U30": float(
                        np.mean([float(row["rmse_vs_same_lambda_U30"]) for row in rows])
                    ),
                    "max_rmse_vs_same_lambda_U30": float(
                        np.max([float(row["rmse_vs_same_lambda_U30"]) for row in rows])
                    ),
                    "mean_improvement_vs_same_lambda_U10_percent": float(
                        np.mean([float(row["improvement_vs_same_lambda_U10_percent"]) for row in rows])
                    ),
                }
            )
    summary_path = write_csv(TABLE_DIR / "lambda_sensitivity_summary.csv", summary_rows)

    stability_rows: list[dict[str, object]] = []
    for layout in layouts:
        if layout.layout_id == "U30_reference":
            continue
        for wavelength_m in wavelengths_m:
            values = [
                float(row["rmse_vs_same_lambda_U30"])
                for row in metric_rows
                if row["layout_id"] == layout.layout_id and int(row["wavelength_m"]) == wavelength_m
            ]
            drift_values = [
                float(row["rmse_vs_lambda_1e-16"])
                for row in drift_rows
                if row["layout_id"] == layout.layout_id and int(row["wavelength_m"]) == wavelength_m
            ]
            mean_value = float(np.mean(values))
            span = float(np.max(values) - np.min(values))
            stability_rows.append(
                {
                    "layout_id": layout.layout_id,
                    "display_name": layout.display_name,
                    "wavelength_m": wavelength_m,
                    "mean_rmse_vs_same_lambda_U30": mean_value,
                    "std_rmse_vs_same_lambda_U30": float(np.std(values)),
                    "relative_span_percent": span / mean_value * 100.0 if mean_value else 0.0,
                    "max_response_drift_rmse_vs_1e-16": float(np.max(drift_values)),
                }
            )
    stability_path = write_csv(TABLE_DIR / "lambda_sensitivity_stability.csv", stability_rows)

    best_rows: list[dict[str, object]] = []
    for relative_lambda in relative_lambdas:
        label = lambda_label(relative_lambda)
        for wavelength_m in wavelengths_m:
            candidates = [
                row
                for row in metric_rows
                if row["lambda_label"] == label
                and int(row["wavelength_m"]) == wavelength_m
                and row["layout_id"] != "U30_reference"
            ]
            best = min(candidates, key=lambda row: float(row["rmse_vs_same_lambda_U30"]))
            uniform_row = next(row for row in candidates if row["layout_id"] == "uniform_U10")
            best_rows.append(
                {
                    "relative_lambda": relative_lambda,
                    "lambda_label": label,
                    "wavelength_m": wavelength_m,
                    "best_layout_id": best["layout_id"],
                    "best_display_name": best["display_name"],
                    "best_rmse_vs_same_lambda_U30": best["rmse_vs_same_lambda_U30"],
                    "uniform_U10_rmse_vs_same_lambda_U30": uniform_row["rmse_vs_same_lambda_U30"],
                    "best_improvement_vs_same_lambda_U10_percent": best[
                        "improvement_vs_same_lambda_U10_percent"
                    ],
                }
            )
    best_path = write_csv(TABLE_DIR / "lambda_sensitivity_best_by_lambda_wavelength.csv", best_rows)
    return metrics_path, summary_path, stability_path, drift_path


def metric_value(
    rows: list[dict[str, str]],
    *,
    layout_id: str,
    lambda_label_value: str,
    wavelength_m: int,
    key: str,
) -> float:
    for row in rows:
        if (
            row["layout_id"] == layout_id
            and row["lambda_label"] == lambda_label_value
            and int(row["wavelength_m"]) == int(wavelength_m)
        ):
            return float(row[key])
    raise KeyError((layout_id, lambda_label_value, wavelength_m, key))


def plot_rmse_vs_lambda(
    *,
    metrics_path: Path,
    relative_lambdas: tuple[float, ...],
    wavelengths_m: tuple[int, ...],
) -> Path:
    import matplotlib.pyplot as plt

    rows = read_csv(metrics_path)
    layouts = [layout for layout in selected_layouts() if layout.layout_id != "U30_reference"]
    sorted_lambdas = tuple(sorted(relative_lambdas))
    labels = [lambda_label(value) for value in sorted_lambdas]

    column_count = 2
    row_count = int(np.ceil(len(wavelengths_m) / column_count))
    fig, axes = plt.subplots(row_count, column_count, figsize=(12.0, 4.2 * row_count), sharex=True)
    axes_flat = np.ravel(axes)
    for axis, wavelength_m in zip(axes_flat, wavelengths_m):
        for layout in layouts:
            values = [
                metric_value(
                    rows,
                    layout_id=layout.layout_id,
                    lambda_label_value=label,
                    wavelength_m=wavelength_m,
                    key="rmse_vs_same_lambda_U30",
                )
                for label in labels
            ]
            axis.plot(
                sorted_lambdas,
                values,
                marker="o",
                linewidth=1.6,
                color=COLORS.get(layout.layout_id, "#666666"),
                label=layout.display_name,
            )
        axis.set_xscale("log")
        axis.axvline(BASELINE_LAMBDA, color="#222222", linewidth=0.9, linestyle=":", alpha=0.8)
        axis.set_title(f"{wavelength_m} m")
        axis.set_ylabel("heave RMSE vs same-lambda U30")
        axis.grid(True, color="#dddddd", linewidth=0.7, alpha=0.85)
    for axis in axes_flat[len(wavelengths_m) :]:
        axis.axis("off")
    for axis in axes_flat[-column_count:]:
        axis.set_xlabel("SEREP-ridge relative lambda")
    axes_flat[0].legend(frameon=False, fontsize=8)
    fig.suptitle("SEREP-ridge lambda sensitivity: heave RMSE", fontsize=15)
    fig.tight_layout(rect=(0, 0, 1, 0.955))
    path = FIGURE_DIR / "lambda_sensitivity_rmse_vs_lambda.png"
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=220)
    plt.close(fig)
    return path


def plot_relative_span_heatmap(stability_path: Path, wavelengths_m: tuple[int, ...]) -> Path:
    import matplotlib.pyplot as plt

    rows = read_csv(stability_path)
    layouts = [layout for layout in selected_layouts() if layout.layout_id != "U30_reference"]
    values = np.asarray(
        [
            [
                next(
                    float(row["relative_span_percent"])
                    for row in rows
                    if row["layout_id"] == layout.layout_id and int(row["wavelength_m"]) == wavelength_m
                )
                for wavelength_m in wavelengths_m
            ]
            for layout in layouts
        ]
    )
    fig, axis = plt.subplots(figsize=(9.8, 4.8))
    image = axis.imshow(values, aspect="auto", cmap="YlGnBu")
    axis.set_xticks(np.arange(len(wavelengths_m)))
    axis.set_xticklabels([str(value) for value in wavelengths_m])
    axis.set_yticks(np.arange(len(layouts)))
    axis.set_yticklabels([layout.display_name for layout in layouts])
    axis.set_xlabel("wavelength (m)")
    axis.set_title("RMSE sensitivity across SEREP-ridge lambda values")
    for row_index in range(values.shape[0]):
        for column_index in range(values.shape[1]):
            axis.text(
                column_index,
                row_index,
                f"{values[row_index, column_index]:.2f}%",
                ha="center",
                va="center",
                fontsize=8,
                color="#111111",
            )
    cbar = fig.colorbar(image, ax=axis)
    cbar.set_label("relative RMSE span across lambdas")
    fig.tight_layout()
    path = FIGURE_DIR / "lambda_sensitivity_relative_span_heatmap.png"
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=220)
    plt.close(fig)
    return path


def plot_best_layout_map(
    *,
    relative_lambdas: tuple[float, ...],
    wavelengths_m: tuple[int, ...],
) -> Path:
    import matplotlib.pyplot as plt
    from matplotlib.colors import ListedColormap

    rows = read_csv(TABLE_DIR / "lambda_sensitivity_best_by_lambda_wavelength.csv")
    layout_codes = {
        "uniform_U10": 0,
        "NU10_center_refined": 1,
        "NU10_edge_mild": 2,
        "NU10_bow_refined": 3,
    }
    layout_labels = {
        "uniform_U10": "U10",
        "NU10_center_refined": "center",
        "NU10_edge_mild": "edge",
        "NU10_bow_refined": "bow",
    }
    sorted_lambdas = tuple(sorted(relative_lambdas, reverse=True))
    labels = [lambda_label(value) for value in sorted_lambdas]
    values = np.zeros((len(labels), len(wavelengths_m)))
    text = [["" for _ in wavelengths_m] for _ in labels]
    for row_index, label in enumerate(labels):
        for column_index, wavelength_m in enumerate(wavelengths_m):
            row = next(
                item
                for item in rows
                if item["lambda_label"] == label and int(item["wavelength_m"]) == wavelength_m
            )
            layout_id = row["best_layout_id"]
            values[row_index, column_index] = layout_codes[layout_id]
            text[row_index][column_index] = layout_labels[layout_id]

    fig, axis = plt.subplots(figsize=(8.8, 4.8))
    cmap = ListedColormap(["#1f77b4", "#ff7f0e", "#9467bd", "#d62728"])
    image = axis.imshow(values, aspect="auto", cmap=cmap, vmin=-0.5, vmax=3.5)
    axis.set_xticks(np.arange(len(wavelengths_m)))
    axis.set_xticklabels([str(value) for value in wavelengths_m])
    axis.set_yticks(np.arange(len(labels)))
    axis.set_yticklabels(labels)
    axis.set_xlabel("wavelength (m)")
    axis.set_ylabel("relative lambda")
    axis.set_title("Best 10-module layout under lambda sensitivity")
    for row_index in range(values.shape[0]):
        for column_index in range(values.shape[1]):
            axis.text(column_index, row_index, text[row_index][column_index], ha="center", va="center", fontsize=8)
    cbar = fig.colorbar(image, ax=axis, ticks=[0, 1, 2, 3])
    cbar.ax.set_yticklabels(["U10", "center", "edge", "bow"])
    fig.tight_layout()
    path = FIGURE_DIR / "lambda_sensitivity_best_layout_map.png"
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=220)
    plt.close(fig)
    return path


def plot_response_drift(drift_path: Path, wavelengths_m: tuple[int, ...]) -> Path:
    import matplotlib.pyplot as plt

    rows = read_csv(drift_path)
    layouts = list(selected_layouts())
    values = np.asarray(
        [
            [
                max(
                    float(row["rmse_vs_lambda_1e-16"])
                    for row in rows
                    if row["layout_id"] == layout.layout_id and int(row["wavelength_m"]) == wavelength_m
                )
                for wavelength_m in wavelengths_m
            ]
            for layout in layouts
        ]
    )
    log_values = np.log10(np.maximum(values, 1.0e-12))
    fig, axis = plt.subplots(figsize=(9.8, 4.8))
    image = axis.imshow(log_values, aspect="auto", cmap="viridis")
    axis.set_xticks(np.arange(len(wavelengths_m)))
    axis.set_xticklabels([str(value) for value in wavelengths_m])
    axis.set_yticks(np.arange(len(layouts)))
    axis.set_yticklabels([layout.display_name for layout in layouts])
    axis.set_xlabel("wavelength (m)")
    axis.set_title("Maximum response drift relative to lambda=1e-16")
    for row_index in range(values.shape[0]):
        for column_index in range(values.shape[1]):
            axis.text(
                column_index,
                row_index,
                f"{values[row_index, column_index]:.2e}",
                ha="center",
                va="center",
                fontsize=8,
                color="white",
            )
    cbar = fig.colorbar(image, ax=axis)
    cbar.set_label("log10(max RMSE drift)")
    fig.tight_layout()
    path = FIGURE_DIR / "lambda_sensitivity_response_drift.png"
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=220)
    plt.close(fig)
    return path


def markdown_table(headers: tuple[str, ...], rows: list[tuple[object, ...]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(":---" if index == 0 else "---:" for index in range(len(headers))) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(value) for value in row) + " |")
    return "\n".join(lines)


def write_report(
    *,
    relative_lambdas: tuple[float, ...],
    wavelengths_m: tuple[int, ...],
    metrics_path: Path,
    summary_path: Path,
    stability_path: Path,
    drift_path: Path,
    master_nodes_path: Path,
    figures: dict[str, Path],
) -> Path:
    best_rows = read_csv(TABLE_DIR / "lambda_sensitivity_best_by_lambda_wavelength.csv")
    stability_rows = read_csv(stability_path)
    drift_rows = read_csv(drift_path)

    best_count_rows = []
    for wavelength_m in wavelengths_m:
        candidates = [row for row in best_rows if int(row["wavelength_m"]) == wavelength_m]
        counts: dict[str, int] = {}
        for row in candidates:
            counts[row["best_display_name"]] = counts.get(row["best_display_name"], 0) + 1
        best_count_rows.append(
            (
                wavelength_m,
                ", ".join(f"{name}: {count}" for name, count in sorted(counts.items())),
                max(counts, key=counts.get),
            )
        )

    span_rows = []
    for layout in [item for item in selected_layouts() if item.layout_id != "U30_reference"]:
        layout_rows = [row for row in stability_rows if row["layout_id"] == layout.layout_id]
        span_rows.append(
            (
                layout.display_name,
                f"{max(float(row['relative_span_percent']) for row in layout_rows):.3f}%",
                f"{np.mean([float(row['relative_span_percent']) for row in layout_rows]):.3f}%",
                f"{max(float(row['max_response_drift_rmse_vs_1e-16']) for row in layout_rows):.3e}",
            )
        )

    drift_max = max(float(row["rmse_vs_lambda_1e-16"]) for row in drift_rows)
    drift_summary_rows = []
    for layout in selected_layouts():
        layout_drift = [float(row["rmse_vs_lambda_1e-16"]) for row in drift_rows if row["layout_id"] == layout.layout_id]
        drift_summary_rows.append((layout.display_name, f"{max(layout_drift):.3e}", f"{np.mean(layout_drift):.3e}"))
    lines = [
        "# SEREP-ridge lambda sensitivity check",
        "",
        "## Scope",
        "",
        "This check varies only the SEREP-ridge relative regularization parameter. "
        "The Capytaine hydrodynamic NetCDF files are reused from the extended wavelength sweep.",
        "",
        f"- Relative lambdas: `{', '.join(lambda_label(value) for value in relative_lambdas)}`",
        f"- Wavelengths: `{', '.join(str(value) for value in wavelengths_m)} m`",
        "- Reference for each lambda: U30 solved with the same lambda.",
        "- Drift baseline: lambda = `1e-16`.",
        "",
        "## RMSE curves",
        "",
        f"![RMSE curves](figures/{figures['rmse'].name})",
        "",
        "## Best-layout stability",
        "",
        f"![Best layout map](figures/{figures['best_map'].name})",
        "",
        markdown_table(("wavelength (m)", "best-count across lambdas", "most frequent best"), best_count_rows),
        "",
        "## Sensitivity magnitude",
        "",
        f"![Relative span](figures/{figures['span'].name})",
        "",
        f"![Response drift](figures/{figures['drift'].name})",
        "",
        markdown_table(("layout", "max RMSE span", "mean RMSE span", "max response drift"), span_rows),
        "",
        markdown_table(("layout", "max drift vs 1e-16", "mean drift vs 1e-16"), drift_summary_rows),
        "",
        f"Maximum response drift relative to lambda=1e-16 across all checked cases: `{drift_max:.3e}`.",
        "",
        "## Output files",
        "",
        f"- Metrics by wavelength: `{metrics_path}`",
        f"- Lambda summary: `{summary_path}`",
        f"- Stability table: `{stability_path}`",
        f"- Response drift table: `{drift_path}`",
        f"- Master-node table: `{master_nodes_path}`",
        f"- Response directory: `{RESPONSE_DIR}`",
        "",
    ]
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    return REPORT_PATH


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--relative-lambdas", default=None, help="comma/space separated values")
    parser.add_argument("--wavelengths", default=None, help="comma/space separated wavelength values in m")
    parser.add_argument("--force-response", action="store_true", help="recompute response npy files")
    args = parser.parse_args()

    relative_lambdas = parse_float_list(args.relative_lambdas, DEFAULT_RELATIVE_LAMBDAS)
    wavelengths_m = parse_int_list(args.wavelengths, DEFAULT_WAVELENGTHS_M)
    if not any(abs(value - BASELINE_LAMBDA) < BASELINE_LAMBDA * 1.0e-12 for value in relative_lambdas):
        raise ValueError("relative lambdas must include 1e-16 for response-drift comparison")

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)

    master_nodes_path = write_master_node_tables(selected_layouts())
    solve_all(
        relative_lambdas=relative_lambdas,
        wavelengths_m=wavelengths_m,
        force_response=args.force_response,
    )
    metrics_path, summary_path, stability_path, drift_path = compute_metrics(
        relative_lambdas=relative_lambdas,
        wavelengths_m=wavelengths_m,
    )
    figures = {
        "rmse": plot_rmse_vs_lambda(
            metrics_path=metrics_path,
            relative_lambdas=relative_lambdas,
            wavelengths_m=wavelengths_m,
        ),
        "span": plot_relative_span_heatmap(stability_path, wavelengths_m),
        "best_map": plot_best_layout_map(relative_lambdas=relative_lambdas, wavelengths_m=wavelengths_m),
        "drift": plot_response_drift(drift_path, wavelengths_m),
    }
    report_path = write_report(
        relative_lambdas=relative_lambdas,
        wavelengths_m=wavelengths_m,
        metrics_path=metrics_path,
        summary_path=summary_path,
        stability_path=stability_path,
        drift_path=drift_path,
        master_nodes_path=master_nodes_path,
        figures=figures,
    )
    print(f"report={report_path}")
    print(f"tables={TABLE_DIR}")
    print(f"figures={FIGURE_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
